version: "3"

services:
  backend:
    container_name: flask-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5001:5000"
    volumes:
      - "flask-backend-volume:/app"


  frontend:
    container_name: flask-react-frontend
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"

volumes:
  flask-backend-volume:
    external: true
